const DELIVERY_STATUSES = Object.freeze([
  'PENDING', 'ASSIGNED', 'PICKUP_PENDING', 'PICKED_UP', 'ON_THE_WAY',
  'DELIVERED', 'FAILED', 'CANCELLED',
]);

const TRANSITIONS = Object.freeze({
  PENDING: ['ASSIGNED', 'CANCELLED'],
  ASSIGNED: ['PICKUP_PENDING', 'FAILED', 'CANCELLED'],
  PICKUP_PENDING: ['PICKED_UP', 'FAILED', 'CANCELLED'],
  PICKED_UP: ['ON_THE_WAY', 'FAILED'],
  ON_THE_WAY: ['DELIVERED', 'FAILED'],
  DELIVERED: [],
  FAILED: [],
  CANCELLED: [],
});

module.exports = { DELIVERY_STATUSES, TRANSITIONS };